ERROR - 2024-12-09 15:33:28 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'itcrush' in C:\xampp\htdocs\itcrush\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\itcrush\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'root', '', 'itcrush', 3306, '', 0)
#1 C:\xampp\htdocs\itcrush\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\itcrush\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\itcrush\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\itcrush\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\itcrush\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\itcrush\app\Controllers\Contact.php(11): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\itcrush\system\CodeIgniter.php(941): App\Controllers\Contact->index()
#8 C:\xampp\htdocs\itcrush\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Contact))
#9 C:\xampp\htdocs\itcrush\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\itcrush\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'itcrush' in C:\xampp\htdocs\itcrush\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\itcrush\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\itcrush\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\itcrush\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\itcrush\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\itcrush\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\itcrush\app\Controllers\Contact.php(11): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\itcrush\system\CodeIgniter.php(941): App\Controllers\Contact->index()
#7 C:\xampp\htdocs\itcrush\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Contact))
#8 C:\xampp\htdocs\itcrush\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\itcrush\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-12-09 15:33:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'itcrush'
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `contact`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Contact.php(11): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Contact->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Contact))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
